name = input("Name:")
age = input("Age:")
subject = input("Subject:")
print("===== My Info Card =====")
print("Name:", name)
print("Age:", age)
print("Subject:", subject)
print("========================")
